# Platform detection and setup
# cross compilation is not supported !

set(QEMUCSD_WINDOWS FALSE)
set(QEMUCSD_LINUX FALSE)
set(QEMUCSD_APPLE FALSE)

if (CMAKE_SYSTEM_NAME STREQUAL "Windows")
    message("${PRJ_PRX}: Operating system: Windows")
    set(QEMUCSD_WINDOWS TRUE)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message("${PRJ_PRX}: Operating system: Linux")
    set(QEMUCSD_LINUX TRUE)
elseif (CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    message("${PRJ_PRX}: Operating system: MacOS")
    set(QEMUCSD_APPLE TRUE)
else ()
    message(FATAL "Operating system not supported!")
endif()

set(QEMUCSD_32BIT FALSE)
set(QEMUCSD_64BIT FALSE)

# Determine bits of address model based on TargetArch.cmake target_architecture result
# this function modifies AIRGLOW_32BIT and AIRGLOW_64BIT
function(determine_address_model architecture)
    if("${architecture}" STREQUAL "arm")
        set(QEMUCSD_32BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "armv5")
        set(QEMUCSD_32BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "armv6")
        set(QEMUCSD_32BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "armv7")
        set(QEMUCSD_32BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "armv8")
        set(QEMUCSD_32BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "aarch64")
        set(QEMUCSD_64BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "i386")
        set(QEMUCSD_32BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "x86_64")
        set(QEMUCSD_64BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "ia64")
        set(QEMUCSD_64BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "ppc")
        set(QEMUCSD_32BIT TRUE PARENT_SCOPE)
    elseif("${architecture}" STREQUAL "ppc64")
        set(QEMUCSD_64BIT TRUE PARENT_SCOPE)
    else()
        message("${PRJ_PRX}: ${architecture} does not match any known strings")
    endif()
endfunction(determine_address_model)